// Base de talents — Agence UBBA
// Source: https://www.ubba.fr

const talentsUBBA = {
  comediens: [
    "Hervé", "Lennikim", "Marwen Zaibat (USKY)", "TAYC", "Guillaume Plas",
    "Mustapha Abourachid", "Anthony Abribacht", "Amine Adjina", "Thomas Agouloye",
    "Hassane Alili", "Louis Andrieu", "Verdy Antsiou", "Pierre Arditi",
    "Louis Arene", "Harrison Arevalo", "Mhamed Arezki", "Samuel Arnold",
    "Mouloud Ayad", "Idir Azougli", "Felix Back", "Arben Bajraktaraj",
    "Jamie Bamber", "Olivier Baroux", "Jean-Marc Barr", "Karim Barras",
    "Maurice Barthelemy", "Julien Baumgartner", "Raymond Baur",
    "Léokim Beaumier-Lépine", "Nathanaël Beausivoir", "Samy Belkessa",
    "Lucas Belvaux", "BEN", "Moustafa Benaibout", "Jean Benguigui",
    "Hubert Benhamdine", "Adem Benosmane", "Eric Berger", "Clément Bertani",
    "Oscar Berthe", "Dominique Bettenfeld", "Etienne Beydon", "Clement Bigot",
    "Benjamin Biolay", "Jonas Bloquet", "Thomas Bodson", "Jean-Edouard Bodziak",
    "Thibault Bonenfant", "Olivier Bonnaud", "Victorien Bonnet", "Bernie Bonvoisin",
    "Melvin Boomer", "Dany Boon", "Félix Bossuet", "Vlad Botnaru", "Younès Bouab",
    "Mourad Bouayad", "Nassim Bouguezzi", "Eric.K Boulianne", "Solal Bouloudnine",
    "Charles Roger Bour", "Saidou Camara", "Guillaume Canet", "Eric Caravaca",
    "Armel Cazedepats", "Baptiste Chabauty", "Louis Chappey", "Bilel Chegrani",
    "Giovanni Cirfiera", "David Clavel", "Benjamin Cléry", "Jean-Charles Clichet",
    "François Cluzet", "Daniel Cohen", "Eliah Cohen", "Arthur Colzy",
    "Jean-Henri Compère", "Shane Copin", "Andrea Cossu", "Jean-Luc Couchard",
    "Thomas Coumans", "Edouard Court", "Johann Cuny", "Soriba Dabo",
    "Adrien Dantou", "Vinnie Dargaud", "Virgile Daudet", "Emmanuel Daumas",
    "François De Brauer", "Thomas de Fouchécour", "Clément Deboeur", "Adil Dehbi",
    "Hugues Delamarlière", "Nelson Delapalme", "Scali Delpeyrat", "Albert Delpy",
    "Esteban Delsaut", "Mathieu Demy", "Vincent Deniard", "Sébastien Depommier",
    "Matthieu Dessertine", "Marcial Di Fonzo Bo", "Djibi Diakhaté",
    "Johann Dionnet", "Aliyou Diop", "Yohan Djabour", "Vernon Dobtcheff",
    "Yanis Doinel", "Laurent d'Olce", "César Domboy", "Thomas Doret",
    "Florent Dorin", "Damien Dorsaz", "Yassine Douighi", "Alain Doutey",
    "Jean-Stan Du Pac", "Anthony Dubos", "Thomas Durand", "Satya Dusaugey",
    "Léonard Dusseau", "Philippe Dusseau", "Ulysse Dutilloy-Liégeois",
    "Nicolas Duvauchelle", "Edouard Eftimakis", "Gedeon Ekay", "Mayel Elhajaoui",
    "Pascal Elso", "Joseph Engel", "Frédéric Epaud", "Mike Etienne",
    "Thibaut Evrard", "Léon Exbrayat", "Denis Eyriey", "Madior Fall",
    "Nemo Féral", "Raphaël Ferret", "Jules Finn", "Clément Fiori",
    "Joaquim Fossi", "Aymeric Fougeron", "Joseph Fourez", "Marc Fraize",
    "FRANGLISH", "Roman Frayssinet", "Julien Frison", "Nordine Ganso",
    "Vincent Garanger", "Gael Garcia Bernal", "Jean-Louis Garçon",
    "Julien Gaspar-Oliveri", "Maxime Gasteuil", "Alix Gavoille", "Valerian Geay",
    "Pierre Gervais", "David Geselson", "Saïd Ghanem", "Romain Gillot",
    "Nicolas Giraud", "Alex Godbout", "Vadiel Gonzalez", "Lazare Gousseau",
    "Tijmen Govaerts", "Douglas Grauwels", "GRINGE", "Diego Guerra",
    "Paul Guion de Meritens", "Guillaume Guisset", "Guillermo Guiz",
    "Alban Guyon", "Jan Hammenecker", "Pierre Hancisse",
    "Thierry Hancisse", "Hadrien Heaulmé", "Ethan Heyler",
    "Noé Houssard", "Marouan Iddoub", "Tewfik Jallab", "Michel Jonasz",
    "Samuel Jouy", "Marin Judas", "Salem Kali", "Martin Karmann", "Rik Kleve",
    "Antoine Kobi", "Diouc Koma", "Taddeo Kufus", "Félix Kysyl",
    "Laurent Lafitte", "Sébastien Lalanne", "Bouli Lanners", "Basile Larie",
    "Joachim Larrieu", "Pierre Louis Laugerias", "Denis Lavant",
    "François Le Bris", "Guy Lecluyse", "Logan Lefebvre", "Lorenzo Lefebvre",
    "Paul Lefevre", "Gilles Lellouche", "Raphaël Lenglet", "Alban Lenoir",
    "Tristan Leroy", "Mathieu Lescop", "Romain Levi", "Max Libert",
    "Sébastien Libessart", "Lionel Lingelser", "Bruno Lopez", "Jeremy Lorca",
    "Arthur Louis-Calixte", "Gaspard Maffre", "Giuseppe Maggio",
    "Benoît Magimel", "Guillaume Marbeck", "Eugène Marcuse", "Enzo Martinez",
    "Simon Masnay", "Yoann Thibaut Mathias", "Arthur Mazet", "Ibrahima Mbaye",
    "Mexianu Medenou", "Louis Meignan", "Lucas Meister", "Louka Meliava",
    "Gilbert Melki", "Kad Merad", "Cyril Metzger", "David Migeot",
    "Patrick Mille", "Benjamin Millepied", "Neil Adam Mohammedi",
    "Franck Monsigny", "Christophe Montenez", "Maxime Motte", "David Mousset",
    "Marc'Antonu Mozziconacci", "Samy Nasri", "Félix Nebel", "Vincent Nemeth",
    "Ferdinand Niquet Rioux", "Eduardo Noriega", "Christophe Ntakabanyura",
    "Tobias Nuytten", "Pascal Oumaklouf", "Delil Ozhan", "Djibril Pavadé",
    "Alexandre Pavloff", "Thierry Peretti", "Nahuel Perez Biscayart",
    "Raphaël Personnaz", "Sebastien Pierre", "Antoine Olivier Pilon",
    "Hugo Plassard", "Benoît Poelvoorde", "Jérôme Pouly", "François Pouron",
    "Vincent Primault", "Jean-Philippe Puymartin", "Olivier Py",
    "Benjamin Ramon", "Denez Raoul", "Jean-Jacques Rausin", "Philippe Rebbot",
    "Ferdinand Regent-Chappey", "Timothée Regnier", "Aliocha Reinert",
    "Jordan Rezgui", "Jules Ritmanic", "John Robinson", "Mathis Roche",
    "Syméon Rohrbach", "Jean-Paul Rouve", "Siméon Ruf", "Ambroise Sabbagh",
    "Fayçal Safi", "Thomas Sagols", "Jordan Sajous", "Emmanuel Salinger",
    "Claudio Santamaria", "Moïse Santamaria", "Nemo Schiffman",
    "Guillaume Schmitt-Bailer", "Emmanuel Schwartz", "Matthias Schweighofer",
    "Waël Sersoub", "Manuel Severi", "Benjamin Siksou", "Thomas Silberstein",
    "Adrien Simion", "Basile Sommermeyer", "Louis Starace", "Edouard Sulpice",
    "Martin Swabey", "Alassane Sy", "Moussa Sylla", "Maxime Taffanel",
    "Merwane Tajouiti", "David Talbot", "Fred Testot", "Samuel Theis",
    "Pierre Thionois", "Simon Thomas", "Christopher Thompson", "Marcel Thompson",
    "Steve Tientcheu", "Enzo Tinebra", "Yann Tregouet", "Alexandre Trocki",
    "Maxence Tual", "Bertrand Usclat", "Charles Van De Vyver",
    "Luc Van Grunderbeeck", "Gaëtan Vassart", "Thomas VDB",
    "Emilien Vekemans", "Constantin Vidal", "Thibault Vinçon", "Padrig Vion",
    "Michel Vuillermoz", "Léo Walk", "Nathan Willcocks", "Frank Williams",
    "Vincent Winterhalter", "Bruno Wolkowitch", "Clyde Yeguete",
    "Chakib Zamzem", "Tristan Zanchi", "Marc Zinga", "Djebril Zonga"
  ],
  comediennes: [
    "Isabel Aimé Gonzalez Sola", "Hannah Abdoh", "Sarah Adler",
    "Marie-France Alvarez", "Angelina Amandio", "Sophia Aram", "Fanny Ardant",
    "Catherine Arditi", "Roxane Arnal", "Laurence Arné", "Constance Arnoult",
    "Gemma Arterton", "June Assal", "Coralie Audret", "Veerle Baetens",
    "Manon Balasuriya", "Marianne Basler", "Ava Baya", "Natalie Beder",
    "Sofia Belabbes", "Nour Belkhiria", "Saül Benchetrit", "Emmanuelle Bercot",
    "Sylvia Berge", "Lola Bessis", "Anna Biolay", "Mathilde Bisson",
    "Lola Blanchard", "Leïla Blier", "Clémence Boissé", "Emma Bojan",
    "Maïmouna Bop Ndiaye", "Inès Boukhelifa", "Charline Bourgeois-Tacquet",
    "Louise Bourgoin", "Mely Bourjac", "Shirley Bousquet", "Eya Bouteraa",
    "Lou-Adriana Bouziouane", "Zabou Breitman", "Caroline Brésard",
    "Pauline Briand", "Lizzie Brocheré", "Marie Bunel", "Xenia Buravsky",
    "Antonia Buresi", "Rosa Bursztein", "Valentine Cadic", "Morgane Cadignan",
    "Stéphane Caillard", "Anne Caillon", "Lili Rose Carlier",
    "Tallulah Cassavetti", "Emilie Cazenave", "Léo Chalié", "Camille Chamoux",
    "Amel Charif", "Martine Chevallier", "Julia Chiche", "Clara Choï",
    "Mei Cirne-Masuki", "Alexandra Cismondi", "Roukiatou Cissé",
    "Laetitia Clément", "Pauline Clément", "Gabrielle Cohen", "Louise Coldefy",
    "Lulja Comar", "Paloma Coquant", "Milya Corbeil-Gauvreau",
    "Salomé Da Souza", "Ludmilla Dabo", "Juliette Damy", "Adilé David",
    "Charlotte De Bruyne", "Laure de Dietrich", "Hortense de Gromard",
    "Julia de Nunez", "Emilie de Preissac", "Jennifer Decker",
    "Catalina Del Rosario", "Julie Delpy", "Florence Denou", "Kelly Depeault",
    "Adeline D'Hermy", "Anna Diakhere Thiandoum", "Aïssatou Diallo Sagna",
    "Claudia Dimier", "Marina Dol", "Marie Dompnier", "Valérie Donzelli",
    "Laetitia Dosch", "Mélanie Doutey", "Mahaut Drama", "Marie Drucker",
    "Victoire Du Bois", "Ilona Dufrene", "Nine d'Urso", "Julie Duval",
    "Victoria Eber", "Emma Ebouaney", "Laëtitia Eïdo", "Vinora Epp",
    "Céline Espérin", "Elisa Ezzedine", "Marianne Fabbro",
    "Clémentine Fargeas-Sichler", "Gioia Farisano", "Marysole Fertard",
    "Ornella Fleury", "Marina Foïs", "Fanny Fourgeaud", "Carole Franck",
    "Déborah François", "Léone François-Janssens", "Julia Franz Richter",
    "Aurore Frémont", "Charlotte Gainsbourg", "Fabienne Galula",
    "Audrey Garcia", "Cecile Garcia Fogel", "Esther Garrel", "Fantine Gelu",
    "Violaine Gillibert", "Anne Girouard", "Valeria Golino",
    "Karine Gonthier-Hyndman", "Lucie Goudeau", "Louisiane Gouverneur",
    "Anouk Grinberg", "Inès Grunenwald", "Lila Gueneau",
    "Caroline Guiela Nguyen", "Lucille Guillaume", "Nora Hamzawi",
    "Oumnia Hanader", "Zita Hanrot", "Fantine Harduin", "Eva Hatik",
    "Alicia Hava", "Alix Henzelin", "Catherine Hosmalin", "Lila Houel",
    "Elodie Huber", "Isabelle Huppert", "Agnès Hurstel", "Olenka Ilunga",
    "Florence Janas", "Yeelem Jappain", "Joséphine Japy", "Jeanne Jestin",
    "Gina Jimenez", "Iris Jodorowsky", "Suzanne Jouannet",
    "Carmen Kassovitz", "Mina Kavani", "Fanta Kebe", "Ameerah Khedhri",
    "Sandrine Kiberlain", "Hande Kodja", "Ophelia Kolb", "D'Johé Kouadio",
    "Nadia Kounda", "Natacha Krief", "Diane Kruger", "Mathilde La Musse",
    "Nadine Labaki", "Mathilde Labarthe", "Marion Lambert", "Lou Lampros",
    "Clara Maria Laredo", "Estelle Larrivaz", "Mélanie Laurent",
    "Zoé Le Gavrian", "Françoise Lebrun", "Julie Ledru", "Aude Leger",
    "Aurore Lévy", "Katia Lewkowicz", "Dea Liane", "Vanessa Liautey",
    "Lise Lomi", "Jeanne Louis-Calixte", "Louise Malek", "Sofiia Manousha",
    "Louise Manteau", "Judith Margolin", "Anne Marivin", "Héloïse Martin",
    "Elia Merlot", "Mathilde Mery", "Marion Mezadorian",
    "Céline Milliat-Baumgartner", "Soliane Moisset", "Alice Moitié",
    "Lilia Monsigny", "Sara Montpetit", "Laura Morante", "Lily Moreau",
    "Nagisa Morimoto", "Kenza Moumou", "Eloïse Mpassi-Nkouikani",
    "Christine Murillo", "Shirel Nataf", "Maë-Lingh Nguyen", "Mina Onnen",
    "Marie-Christine Orry", "Elise Otzenberger", "Sabrina Ould Hammouda",
    "Sarah Pachoud", "Géraldine Pailhas", "Joanne Palmaro", "Marie Papillon",
    "Alysson Paradis", "Ji-Min Park", "Prune Pauchet", "Anne-Valérie Payet",
    "Marie-Aurélie Penarrubia-Marcos", "Juliette Perez", "Morgane Polanski",
    "Marilou Poujardieu", "Isaline Prévost Radeff", "Audrey Price",
    "Edith Proust", "Laura Puech", "Maïka Radigales", "Romane Raffin-Delys",
    "Farida Rahouadj", "Raph", "Nahéma Ricci", "Zélie Rixhon",
    "Malena Roche", "Clémence Rochefort", "Lucile Rose", "Olivia Ross",
    "Camille Rowe", "Adèle Royné", "Jeanne Ruff", "Véronique Ruggia Saura",
    "Coralie Russier", "Babetida Sadjo", "Erika Sainte", "Sandrine Salyères",
    "Noémie Schmidt", "Adélaïde Schoofs", "Salomé Scotto", "Arièle Semenoff",
    "Anne Serra", "Hélène Seuzaret", "Anne Sila", "Raphaëlle Simon",
    "Juliette Speck", "Anne Suarez", "Mara Taquin", "Lauréna Thellier",
    "Mélissa Thenier", "Marguerite Thiam", "Lou Thompson", "Chine Thybaud",
    "Juliette Tomyn", "Shiraz Tzarfati", "Nelia Valery", "Karine Vanasse",
    "Alice Varela", "Anamaria Vartolomei", "Paloma Vauthier", "Cindy Vincent",
    "Maya Vincent", "Héloïse Volle", "Mona Walravens", "Mathilde Warnier",
    "Alison Wheeler", "Judith Williquet", "Maud Wyler", "Zaïna Yalioua",
    "Iliana Zabeth", "Esther Zajtmann", "Lucie Zhang", "Judith Zins"
  ],
  agence: "UBBA"
};

export default talentsUBBA;
