// Base de talents — Agence CinéArt
// Source: Talents.xlsx

const talentsCineArt = {
  comediens: [
    "Big John", "Adda Abdelli", "Janis Abrikh", "Edward Akrout", "Christophe Alévêque",
    "Hakim Ali", "Gil Alma", "Saïd Amadis", "Emile Arnaud", "David Azencot",
    "Julien Baptist", "Boris Baroux", "Christopher Bayemi", "Madi Belem",
    "Habib Ben Tanfous", "Nicolas Berno", "Pierre Berriau", "Jibril Bhira",
    "Stéphane Blancafort", "Fred Blin", "Liviu Bora", "Simon Boublil",
    "Hedi Bouchenafa", "Eric Boucher", "Kader Boukhanef", "Dorian Boyer-Defoi",
    "Hugo Brunswick", "Aurélien Caeyman", "Maxime Calicharane", "Martin Campestre",
    "Lucas Chérubin", "Walid Chokhman", "Hocine Choutri", "Hans Peter Cloos",
    "Jean Noël Cnokaert", "Malcolm Conrath", "Julien Courbey",
    "Roman Coustere Hachez", "Bernard Crombey", "Eric Da Costa", "Isaach De Bankolé",
    "Vincent De Bouard", "Nicolas De Broglie", "Romaric De La Simone",
    "Eric De Montalier", "Maxime De Toledo", "Patrick De Valette", "Bruno Debrandt",
    "Jules Debuyst", "Sloan Decombes", "Dimitri Defontaine", "Hubert Delattre",
    "Jean Dell", "Xavier Deranlot", "Raphaël Descraques", "Rémi Devilla",
    "Adrien Dewitte", "Waly Dia", "Philippe Du Janerand", "Guillaume Ducreux",
    "Baptiste Dupuy", "Philippe Duquesne", "Karim Duval", "Bilal El Atreby",
    "Amir El Kacem", "Pierre Elliott", "Michael Erpelding", "Bernard Farcy",
    "Frédéric Fisbach", "Alain Floret", "Jake François", "Nhoa François",
    "Philippe Fretun", "Eliott Furic", "Guillaume Gabriel", "Agustín Galiana",
    "Elliot Goldberg", "Xavier Goulard", "François Guetary", "Benjamin Hauser",
    "Dylan Hawkes", "Galiam Bruno Henry", "Freddie Highmore", "Jules Houplain",
    "Roberto Jean", "Billy Johansson", "Toby Jones", "Julien Josselin",
    "Vincent Jouan", "Benoit Joubert", "Hugues Jourdain", "Gaël Kamilindi",
    "Bamar Kane", "Sam Karmann", "Richard Keep", "Harvey Keitel", "Atmen Kelif",
    "Daniel Kenigsberg", "Oussama Kheddam", "Edwin Kruger", "Dhafer L'Abidine",
    "Martin Lamotte", "Eric Lampaert", "Romain Lancry", "Bernard Lanneau",
    "Titouan Laporte", "Ayoub Layoussifi", "Paul Le Bourdon", "Stylane Lecaille",
    "Jean-Claude Lecas", "Eddy Leduc", "Jules Lefebvre", "Philippe Lelievre",
    "Oscar Lesage", "François Levantal", "Milo Machado-Graner",
    "Solàn Machado-Graner", "Arnaud Maillard", "François Mallet",
    "Nicolas Martinez", "Doudou Masta", "Aïssam Medhem", "Ambroise Michel",
    "Jules Miesch", "Mikaël Mittelstadt", "Anthony Morganti",
    "Pierre-Marie Mosconi", "Nicolas Mouen", "Frédéric Moulin",
    "Rabah Nait Oufella", "James Nesbitt", "Thierry Neuvic", "Tanguy Onakoy",
    "Benzola Ortiz Billot", "Olivier Pajot", "Harmandeep Palminder", "Yann Papin",
    "Valentin Papoudof", "Augustin Passard", "Jérémie Petrus", "Matthieu Pillard",
    "Joffrey Platel", "Enzo Porsia", "Pietro Porsia", "Eric Poulain",
    "Léonard Prain", "Lucas Prisor", "Giovanni Pucci", "François Rabette",
    "Jessé Remond Lacroix", "Vincent Rialet", "Jean-Philippe Ricci", "Thomas Rio",
    "Abel Rozé", "Laurent Saint-Gérard", "Pierre Samuel", "Loïs Schlieper",
    "Charles Schneider", "Volodia Serre", "Jacques Serres", "Noam Sinseau",
    "Anthony Sonigo", "Adrien Stoclet", "Surho Sugaipov", "Boris Terral",
    "Philippe Torreton", "Julien Tortora", "Gilles Treton",
    "Frederic Van Den Driessche", "Alexis Van Stratum", "Miguel Vander Linden",
    "Jean-Jacques Vanier", "Vincent Vermignon", "Philippe Vieux", "Adrien Wadih",
    "Stephan Wojtowicz", "Alexandre Zambeaux", "Luca Zingaretti", "Mouss Zouheyri"
  ],
  comediennes: [
    "Nathalia Acevedo", "Aggy K. Adams", "Milla Agid", "Darina Al Joundi",
    "Charifa Ali", "Anissa Allali", "Souad Arsane", "Stéphanie Atala",
    "Brigitte Aubry", "Maud Baecker", "Spencer Barret", "Elodie Batard Gaultier",
    "Astrid Bayiha", "Frédérique Bel", "June Benard Gourion", "Nassima Benchicou",
    "Marie Berto", "Cosima Bevernaege", "Joyce Bibring", "Meryl Bie",
    "Anne-Elisabeth Blateau", "Sophie Bouilloux", "Selma Boukhanef",
    "Carol Brenner", "Sophie Broustal", "Florence Cabaret", "Céline Camara",
    "Valentine Carette", "Nastasia Caruge", "Sarah Cavalli", "Julie Cecchini",
    "Nathalie Cerda", "Louise Charbonnel", "Emilie Chesnais", "Christelle Chollet",
    "Christiane Cohendy", "Sophie Condette", "Eléonore Costes", "Raphaëlle Costes",
    "Tiph Courau", "Anaïs Croze", "Adrienne D'Anna", "Sarah Dambre",
    "Lola Daniel", "Naelle Dariya", "Sophie De La Rochefoucauld",
    "Antonia de Rendinger", "Camille de Sablet", "Grétel Delattre",
    "Mélanie Delloye", "Louise Depardieu", "Charlotte Deslions",
    "Lisa Do Couto Teixeira", "Laura Domenge", "Alice Dubois", "Maïlys Dumon",
    "Tessa Dumont-Janod", "Anny Duperey", "Hanane El Yousfi",
    "Délia Espinat Dief", "Anaïs Fabre", "Zoé Fauconnet", "Lola Felouzis",
    "Andréa Ferreol", "Iliana Ferroudj", "Marie Fevre-Scheuermann",
    "Elodie Galmiche", "Fleur Geffrier", "Poundo Gomis", "Lubna Gourion",
    "Adriane Gradziel", "Hermine Granville", "Louison Grimaldi",
    "Anne-Laure Gruet", "Ada Harb", "Anne-Solenne Hatte", "Pauline Haudepin",
    "Elodie Hesme", "Jennifer Heylen", "Luna Hô Poumey", "Tadrina Hocking",
    "Rehin Hollant", "Héloïse Janjaud", "Marine Jouhet", "Djinda Kane",
    "Matilda Kime", "Nathalie Krebs", "Elise Larnicol", "Justine Le Pottier",
    "Lilou Le Sergent", "Juliane Lepoureau", "Sévane Lepoureau",
    "Kahina Lespert Rolland", "Sylvie Loeillet", "Karina Lombard", "Tanya Lopert",
    "Manon Maindivide", "Sofiia Malovatska", "Toufan Manoutcheri",
    "Sophie Marechal", "Karina Marimon", "Peggy Martineau", "Lisa Martino",
    "Bouraouïa Marzouk", "Ines Masen", "Cassiopée Mayance", "Sfaya Mbarki",
    "Réhab Méhal", "Vanessa Missé", "Nadège Mongerard", "Ariane Mourier",
    "Sophie Mousel", "Lydie Muller", "Elena Nagapetyan", "Farida Ouchani",
    "Fannie Outeiro", "Sabine Pakora", "Adrienne Pauly", "Hélène Péquin",
    "Noëlle Perna", "Marie Petiot", "Aurélia Poirier", "Luisa Ranieri",
    "Isabelle Rattier", "Joana Ribeiro", "Joely Richardson", "Lou Naé Riva",
    "Selma Rodot", "Sonia Rolland", "Stana Roumillac", "Lucile Roussel-Orphelin",
    "Neva Roussel-Orphelin", "Lola Rouzaud", "Céline Samie", "Julie Sassoust",
    "Milla Savarese", "Marion Seclin", "Samira Sedira", "Amou Tati",
    "Dorothée Tavernier", "Clémence Thioly", "Frédérique Tirmont",
    "Marie Torreton", "Esther Van Den Driessche", "Elodie Varlet",
    "Astrid Veillon", "Sara Verhagen", "Lucile Vignolles", "Séverine Vincent",
    "Emeline Weickmans", "Juliette Wiatr", "Sophia Yamna", "Margaret Zenou",
    "Clara Zhang"
  ],
  agence: "CinéArt"
};

export default talentsCineArt;
