// Base de talents — Agence Time Art
// Source: https://www.timeart.fr

const talentsTimeArt = {
  comediens: [
    "Ali Abdellatif", "Samuel Achache", "Walid Afkir", "Gabriel Almaer", "Foëd Amara",
    "Yannis Amouroux", "Richard Anconina", "Luc Antoni", "Logann Antuofermo", "Swann Arlaud",
    "Lionnel Astier", "Clément Aubert", "Jonas Bachan", "Serge Bagdassarian",
    "Max Baissette de Malglaive", "Jean-François Balmer", "Claes Bang", "Etienne Baret",
    "Paul Barki", "Colin Bates", "Amir Baylly", "Arthur Beaudoire", "Xavier Beauvois",
    "Sacha Béhar", "Valérian Behar-Bonnet", "Benjamin Bellecour", "Frank Bellocq",
    "Khaled Benaissa", "Maxence Bendjelloun", "Fehdi Bendjima", "Younès Bendjima",
    "Ilian Bergala", "Charles Berling", "Emile Berling", "Bastien Bernini",
    "Dominique Besnehard", "Jules Béziat", "Benoit Blanc", "Alexandre Blazy",
    "Mazigh Bouaïch", "Nicolas Bouchaud", "Guillaume Bouchède", "Younès Boucif",
    "Nedjim Bouizzoul", "Matthieu Boujenah", "Michel Boujenah", "Ewan Bourdelles",
    "Didier Bourdon", "Djanis Bouzyani", "Calixte Broisin-Doutaz", "Xavier Brossard",
    "Patrick Bruel", "Rasha Bukvic", "Matthieu Burnel", "Pierre Cachia",
    "Baptiste Caillaud", "Robert Cantarella", "Eric Cantona", "Wilfried Capet",
    "Laurent Caron", "Mathieu Carrière", "Baptiste Carrion-Weiss", "Adrien Casse",
    "Audran Cattin", "Lucas Cenciai", "Jules Cherbonnier", "Mikael Chirinian",
    "Théo Christine", "Lamine Cissokho", "Stany Coppet", "Slimane Dazi",
    "Antoine De Foucauld", "Laurent de Montalembert", "Olivier Debbasch", "Samir Decazza",
    "Pierre Delage", "Quentin Delcourt", "Théo Delezenne", "Pascal Demolon",
    "Guillaume Denaiffe", "Arnaud Denis", "Wallerand Denormandie", "Cyril Descours",
    "Alexandre Desjonqueres", "Félix Detours", "Lucas Devin", "Jammeh Diangana",
    "Oumar Diaw", "Gregoire Didelot", "August Diehl", "Adama Diop", "Mostéfa Djadjam",
    "Bristel Djani", "Adel Djemai", "Alexis Driollet", "Julien Drion",
    "Ivan Du Pontavice", "Hervé Dubourjal", "Arnaud Ducret", "Zakaria El Baialy",
    "Pascal Elbé", "Loup-Denis Elion", "Vincent Escure", "Lord Esperanza", "Esteban",
    "Rupert Everett", "Giacomo Fadda", "Moncef Farfar", "Christophe Favre",
    "Michel Ferracci", "Didier Flamand", "Matthias Fortune", "Ruben Freiss",
    "Stéphane Freiss", "Adam Gabay", "Sasson Gabay", "Yann Gael", "Jérémie Galiana",
    "Gaetan Garcia", "Hugo Diego Garcia", "Kevin Garnichat", "Emmanuel Gasne",
    "Jonathan Genet", "Eric Genovese", "Gaspard Gevin-Hié", "Jérémy Gillet",
    "Daniel Gimenez Cacho", "Hippolyte Girardot", "Nicolas Giraud", "Nicolas Godart",
    "Julien Goetz", "Anthony Goffi", "Ash Goldeh", "Bruno Gouery", "Antoine Gourlier",
    "Hammou Graia", "Théo Gross", "Simon Guelat", "Stephan Guerin-Tillié",
    "Dominique Guillo", "Stéphane Guillon", "Ronald Guttman", "Amir Haddad",
    "Adam Hafsia", "Tsahi Halevi", "Paul Hamy", "Redouanne Harjane", "Narayan Hecter",
    "Johan Heldenbergh", "Pierre Helie", "Ivan Herbez", "Jacky Ido", "Ethann Isidore",
    "Kevin Janssens", "Paul Jeanson", "Brontis Jodorowsky", "Yvain Juillard",
    "Roman Kané", "Azedine Kasri", "Mathieu Kassovitz", "Reda Kateb",
    "Mohamed Ketfi", "Sébastien Kheroufi", "Shems Khettouch", "Pierre Kiwitt",
    "Clément Koch", "Stefan Konarske", "Maxence Laperouse", "Alex Lawther",
    "Aidan le Groumellec", "Sammy Lechea", "Radouan Leflahi", "Zacharie Lenglet",
    "Luigi Li", "Jérémie Lippmann", "Bruno Lochet", "Sergi López", "Alexis Loret",
    "Olivier Loustau", "Grégoire Ludig", "Daniel Lundh", "Léo-Antonin Lutinier",
    "Xavier Maly", "Frederic Maranber", "Ugo Marchand", "Mounir Margoum",
    "David Marsais", "François Marthouret", "Vincent Martin", "Toussaint Martinetti",
    "Baptiste Masseline", "Jean-Baptiste Maunier", "Moustapha Mbengue", "Jamil McCraven",
    "Omar Mebrouk", "Tigran Mekhitarian", "Omid Memar", "Adrien Menielle",
    "Robinson Mensah Rouanet", "Abdelhafid Metalsi", "Eric Metayer",
    "Minas Milad Qarawany", "Pablo Mira", "Alexis Moncorgé", "Julien Moreau",
    "Lucas Mortier", "Yannick Morzelle", "Denis Mpunga", "Yvo Muller", "Yoni Nahum",
    "Naïm", "Yvan Naubron", "Jacky Nercessian", "Emmanuel Noblet", "Frank Onana",
    "Orelsan", "Louis Ould Yaou", "Anatolii Panchenko", "Matthieu Penchinat",
    "Darko Perik", "Vladimir Perrin", "Andrea Pittorino", "Ben PLG", "Gaspard Proust",
    "Eric Pucheu", "Alex Ramirès", "Ola Rapace", "Quentin Raymond", "Aurélien Recoing",
    "Pierre Richard", "Patrick Ridremont", "Loïc Riewer", "Massimo Riggi", "Marc Riso",
    "Dylan Robert", "Nino Rocher", "Cookie Kunty / Romain Eck", "Andrea Romano",
    "Chems Romdhani", "Fabrizio Rongione", "Gaëtan Roussel", "Clément Roussier",
    "Daniel Russo", "Medi Sadoun", "Odah Sama", "Abou Sangare", "Paul Scarfoglio",
    "Victor Scarnier", "Volodia Schneider", "Mohamed Seddiki", "Louis Seguier",
    "Maxence Seva", "Augustin Shackelpopoulos", "Morgan Simon", "Abdulah Sissoko",
    "Jules Sitruk", "Clément Solignac", "Paul Spera", "Stanislas Stanic",
    "Robinson Stevenin", "Cyrille Thouvenin", "Marc Tourneboeuf", "Mathieu Touzé",
    "Benjamin Tranié", "Louis Trégant", "Martin Tronquart", "Brett Tucker",
    "Bertrand Uzeel", "Christophe Vandevelde", "Vincent Vanhée", "Tom Villa",
    "Alex Vizorek", "Benjamin Voisin", "Nicolas Wanczycki", "Gabriel Washer",
    "Sefa Yeboah", "Simon Zampieri", "Fabio Zenoni"
  ],
  comediennes: [
    "Camille", "Susana Abaitua", "Mathilde Abd-El-Kader", "Yaël Abecassis",
    "Loubna Abidar", "Louise Adda", "Mélodie Adda", "Sarah Afchain",
    "Nor El Houda Afifi", "Camille Aguilar", "Selma Alaoui", "Sveva Alviti",
    "Caroline Ami", "Elena Anaya", "Eugénie Anselin", "Rachel Arditi", "Marine Arena",
    "Marine Arlen", "Carla Audebaud", "Lubna Azabal", "Claudia Bacos",
    "Louna Balavoine", "Enya Baroux", "Stéphanie Bataille", "Ophélie Bau",
    "Marie-Julie Baup", "Nathalie Baye", "Coline Béal", "Zbeida Belhajamor",
    "Pauline Belle", "Aïcha Ben Miled", "Lina Benzerti", "Mona Berard",
    "Chanelle Bernard", "Maryne Bertieaux", "Sarah Biasini", "Ana Blagojevic",
    "Sandrine Blancke", "Thylane Blondeau", "Clémence Boisnard", "Agathe Bonitzer",
    "Lucie Borleteau", "Nil Bosca", "Raphaèle Bouchard", "Laura Boujenah",
    "Emma Boulanouar", "Chrystal Boursin", "Suliane Brahim", "Rachida Brakni",
    "Zélie Brault", "Roxane Bret", "Anne Brochet", "Aurore Broutin",
    "Christine Brücher", "Daphné Bürki", "Evelyne Buyle", "Noémie Caillault",
    "Stéphanie Caillol", "Joséphine Callies", "Marie-Gaëlle Cals",
    "Maria Fernanda Candido", "Lucrèce Carmignac", "Adèle Castillon",
    "Valentina Cervi", "Rosalie Charrier", "Emilie Charriot", "Margaux Chatelier",
    "Chloé Chaudoye", "Lou Chauvain", "Bénédicte Choisnet", "Christine Citti",
    "Camille Claris", "Aurore Clément", "Romane Colonna Cesari", "Esther Comar",
    "Marie-Sohna Condé", "Manon Coquerel", "Margot Coriolan", "Laurence Côte",
    "Yamée Couture", "Enola Cox", "Alicia Dadoun", "Béatrice Dalle",
    "Alice Daubelcour", "Cécile de France", "Sophie De Fürst",
    "Joséphine De La Baume", "Camille de La Poëze", "Noémie de Lattre",
    "Alice de Lencquesaing", "Juliette Delacroix", "Philippine Delaire",
    "Eugénie Derouand", "Ines Derreumaux", "Charlotte Des Georges", "Luna Desmeules",
    "Alice D'Hauwe", "Coline D'Inca", "Lou Doillon", "Hilda Amira Douaouda",
    "Déborah Dozoul", "Agathe Dronne", "Manon Drugmant", "Colombe Ducrot",
    "Sophie Duez", "Giulia Dussollier", "Tania Dutel", "Myriam El Ghali-Lang",
    "Eurydice El-Etr", "Lauriane Escaffre", "Fanny Esteve", "Nawelle Evad",
    "Lucie Fagedet", "Sonia Faïdi", "Florence Fauquet", "Juliette Fayet",
    "Sara Fazilat", "Jade Fehlmann", "Kenza Fortas", "Jade Fortineau",
    "Brigitte Fossey", "Caroline Fouilhoux", "Elodie Frenck", "Charlotte Gabris",
    "Constance Gay", "Marine Gesbert", "Raphaële Godin", "Naian González Norvind",
    "Gwendolyn Gourvenec", "Céline Groussard", "Chloé Groussard", "Orane Hadjadj",
    "Lou-Anna Hamon", "Naima Hebrail Kidjo", "Anne-Lise Heimburger", "Holy Fatma",
    "Manal Issa", "Nathalie Issa", "Léa Issert", "Mélissa Izquierdo",
    "Adèle Journeaux", "Kayije Kagame", "Lindsay Karamoh", "Valérie Keruzoré",
    "Anne Kessler", "Angélique Kidjo", "Nastassja Kinski", "Khadija Kouyaté",
    "Jade Labeste", "Amélia Lacquemant", "Pia Lagrange", "Audrey Lamy",
    "Chantal Lauby", "Annick Le Goff", "Théa Le Groumellec", "Isabelle Le Nouvel",
    "Julia Lebib", "Lucie Lebrun", "Virginie Ledoyen", "Emilie Lehuraux",
    "Louise Leroy", "Malonn Lévana", "Charlotte Levy", "Marilyn Lima",
    "Pilar Lopez De Ayala", "Déborah Lukumuena", "Matilda Lutz", "Tatty Macleod",
    "Benicia Makengele", "Ludmilla Makowski", "Méliane Marcaggi",
    "Elisabeth Margoni", "Lucile Marquis", "Dany Martial", "Corinne Masiero",
    "Ariane Massenet", "Louise Massin", "Ines Melab", "Chloé Ménager",
    "Annie Mercier", "Hélène Merlin", "Camille Métayer", "Eminé Meyrem",
    "Léa Millet", "Camille Millot Chauvelot", "Miou-Miou", "Sandrine Molaro",
    "Louise Monot", "Chloé Mons", "Kate Moran", "Blanche Morenville",
    "Sabila Moussadek", "Camille Moutawakil", "Patience Munchenbach",
    "Marie Narbonne", "Lola Naymark", "Nelligan", "Caroline Nicoullaud",
    "Wendy Nieto", "Rose Noël", "Lisa Nyarko", "Bulle Ogier", "Sandra Parfait",
    "Anne Parillaud", "Charline Paul", "Olivia Pavlou-Graham", "Lila Pelissier",
    "Fotinì Peluso", "Marguerite Perrotte", "Julia Piaton", "Pharell Pisieczko",
    "Clara Ponsot", "Alkistis Poulopoulou", "Eva Rami", "Charlotte Rampling",
    "Clothilde Raskin", "Chloé Réjon", "Line Renaud", "Eloïse Rey", "Luna Ribeiro",
    "Salomé Richard", "Joy Rieger", "Isabella Rossellini", "Julia Roy",
    "Aurélie Saada", "Sarah-Cheyenne", "Zoé Schellenberg", "Barbara Schulz",
    "Sara Serraiocco", "Julie Sicard", "Caroline Silhol", "Adèle Simphal",
    "Laura Smet", "Soko", "Chloé Stefani", "Alexandra Stewart", "Barbara Sukowa",
    "Assa Sylla", "Anne-Laure Tondu", "Zineb Triki", "Eliane Umuhire",
    "Lena Urzendowsky", "Marine Vacth", "Manon Valentin", "Marie-Camille Valot",
    "Thaïs Vauquières", "Mélodie Vaxelaire", "Laetitia Vercken",
    "Tatiana Verstraeten", "Alice Vial", "Salomé Villiers", "Marina Vlady",
    "Gaia Weiss", "Elodie Yung"
  ],
  agence: "Time Art"
};

export default talentsTimeArt;
